[options]
admin_passwd = CAMBIA_ESTA_MASTER_PASSWORD_LARGA

data_dir = /var/lib/odoo

; Ajusta estas rutas según la estructura real de tu carpeta enterprise:
; Si dentro de /opt/odoo19-docker/addons/enterprise ves muchos módulos (carpetas) como web_enterprise, etc.,
; entonces usa /mnt/extra-addons/enterprise.
; addons_path = /mnt/extra-addons/enterprise,/mnt/extra-addons/custom,/usr/lib/python3/dist-packages/odoo/addons
addons_path = /mnt/extra-addons/enterprise,/usr/lib/python3/dist-packages/odoo/addons

; Si vas a usar proxy (Traefik/Nginx/Caddy)
proxy_mode = True

; en produccion editar desde aquí
; db_name = primera
; list_db = False
; dbfilter = primera
; editar hasta aquí

; Si usas 1 dominio por DB (recomendado)
; dbfilter = ^%d$

http_interface = 0.0.0.0

; Performance
; Ajustar según CPU (workers = CPU_cores * 2 + 1)
workers = 4
max_cron_threads = 2
db_maxconn = 64
; 2.5 GiB
limit_memory_hard = 2684354560
; 2 GiB
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 600
limit_time_real = 1200